apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-nginx-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: custom-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: custom-nginx
    spec:
      containers:
      - name: custom-nginx
        image: gitlab-registry.jklug.work/root/gitlab-k8s-container:latest
        ports:
        - containerPort: 80
